### ISSUE TITLE
Patch 1.0.0 - Roadmap

### ISSUE THREAD

**Issue by tristantheb** [tristantheb/JSCalculator#1]
# Global Additions:

- [x] Structure of the calculator (HTML)
- [x] Design of the calculator (CSS)
- [x] Basic fonctionnalities (0-9, /, *, -, +, =)
- [x] Memories
- [x] Condition to block the additionnal operator after an operator
- [x] Regex to block multi decimal

## Cleanup

- [x] Cleaned JS File
- [x] Cleaned CSS File
- [x] Cleaned HTML File
- [x] Clean documentation

## Live test
[The JS Calculator](https://tristantheb.github.io/JSCalculator/)

**Comment by tristantheb** [comment]
Cleanup of files JS, CSS and clean documentation : Check

**Comment by tristantheb** [comment]
Released version
